// @ts-nocheck all properties not set here are set on creation

export type Equipment = {
	name: string; //eg Cannon
	ac: number | ["ih", number]; //eg ac15 or ih+3 (ih = inherit from parent ship)
	maxhp: number; //eg 50hp
	weight: number; //eg 5 tons
	price: number; //eg 70gp
	tohit: number; //eg +6 to hit
	range: [number, number]; //eg 60/120
	damage: [number, number]; //eg 2d6
	description: string; //eg "Required position: Helm"

	pos: "fore" | "aft" | "port" | "starboard"; //for internal use (if n/a use fore)
	hp: number | string; //for internal use
	id: number; //for internal use
};
export type ShipCargo = {
	name: string; //eg Molasses
	weight: number; //eg 2 tons
	id: number; //for internal use
};
export type Ship = {
	name: string; //eg The Salty Sailor
	class: string; //eg Brigantine
	price: number; //eg 1000gp
	ac: number; //eg ac18
	maxhp: number; //eg 120hp
	storage: number; //eg 12 tons
	speed: number; //eg 45 feet
	crew: [number, number]; //eg 4/9
	equipment: Equipment[]; //eg [Cannon, Harpoon]
	notes: string; //eg "Hull shows signs of frequent repairs. Wheel is made of gold"

	cargo: ShipCargo[]; //for internal use
	keep: boolean; //for internal use
	hp: number | string; //for internal use
	initiative: number; //for internal use
};
export type Player = {
	name: string;
	ac: number;
	initBonus: number;
	passivePerception: number;
	maxhp: number;

	notes: string;
	hp: number | string;
	initiative: number;
	keep: boolean;
	color: string;
};
export const NormalPlayerStats: Player = {
	name: "Steve",
	ac: 14,
	initBonus: 3,
	passivePerception: 12,
	maxhp: 15,
	notes: "Very chiseled chin",
	hp: -1,
	initiative: -1,
	keep: true,
	color: "teal",
};
export type Enemy = {
	name: string;
	ac: number;
	initBonus: number;
	maxhp: number;

	notes: string;
	hp: number | string;
	initiative: number;
	keep: boolean;
};
export const NormalEnemyStats: Enemy = {
	name: "Bandit",
	ac: 13,
	initBonus: 1,
	maxhp: 10,
	notes: "Super evil. Wants to slap your feet with a pickle.",
	hp: -1,
	initiative: -1,
	keep: true,
};
export const EQUIPMENT: { [index: string]: Equipment } = {
	CANNON: {
		name: "Cannon",
		ac: 18,
		maxhp: 55,
		weight: 2,
		price: 60,
		tohit: 4,
		range: [60, 300],
		damage: [5, 10],
		description: "Requires position [Cannon]",
	},
	HARPOON: {
		name: "Harpoon",
		ac: 15,
		maxhp: 40,
		weight: 1.5,
		price: 40,
		tohit: 6,
		range: [20, 60],
		damage: [1, 10],
		description: "Requires position [Harpoon]",
	},
	BALLISTA: {
		name: "Ballista",
		ac: 18,
		maxhp: 50,
		weight: 2.5,
		price: 70,
		tohit: 7,
		range: [120, 480],
		damage: [3, 10],
		description: "Requires position [Ballista]",
	},
	GROUNDING_STONE: {
		name: "Grounding Stone",
		ac: -1,
		maxhp: 20,
		weight: 0.5,
		price: 30,
		description:
			"Each time a spell is cast on this ship the stone loses 1hp and the spellcaster takes 1d8 dmg unless they suceed a dc13 int save",
	},
	FLOATS: {
		name: "Floats",
		ac: 9,
		maxhp: 15,
		weight: -3,
		price: 15,
		description: "Each float gives +3 storage but reduces speed by 5",
	},
	RAM_HEAD: {
		name: "Ram Head",
		ac: ["ih", 3],
		maxhp: 80,
		weight: 7,
		price: 90,
		description: "Roll one less die for crash damage when ramming",
	},
	SAILS: {
		name: "Sails",
		ac: ["ih", 1],
		maxhp: 20,
		weight: 0,
		price: 0,
		description:
			"The mast is a little harder to hit than the hull, but if it goes down, good luck moving",
	},
	MASTERFUL_SAILS: {
		name: "Masterful Sails",
		ac: ["ih", 2],
		maxhp: 35,
		weight: 0,
		price: 60,
		description: "The mast for these sails is made out of the finest wood",
	},
	TARGOSIAN_SAILS: {
		name: "Targosian Sails",
		ac: ["ih", 3],
		maxhp: 60,
		weight: 0,
		price: 130,
		description:
			"+5 to speed. The shipwrights from Targos are well known for their excellent craftsmanship and sturdy sails",
	},
	TARGOSIAN_CANNON: {
		name: "Targosian Cannon",
		ac: 19,
		maxhp: 70,
		weight: 5,
		tohit: 5,
		range: [100, 500],
		damage: [7, 12],
		price: 300,
		description:
			"A beautiful cannon from the port city of Targos. Requires position [Cannon]",
	},
	DINGY: {
		name: "Dingy",
		ac: 14,
		maxhp: 50,
		weight: 2,
		price: 150,
		description:
			"A dingy, or rowboat, assists the crew of large ships in getting to shore. Also acts as a lifeboat.",
	},
};
export const QuickQuips = Object.values(EQUIPMENT).map(
	(a) => a.name + ` (${a.price}gp, ${a.weight} tons)`
);
export const ships: Ship[] = [
	{
		class: "Dingy",
		price: 130,
		ac: 14,
		maxhp: 50,
		storage: 2,
		speed: 30,
		crew: [1, 3],
		equipment: [],
		notes: "",
	},
	{
		class: "Junk",
		price: 400,
		ac: 15,
		maxhp: 80,
		storage: 7,
		speed: 35,
		crew: [2, 5],
		equipment: [EQUIPMENT.HARPOON, EQUIPMENT.SAILS],
		notes: "",
	},
	{
		class: "Corvette",
		price: 650,
		ac: 14,
		maxhp: 95,
		storage: 9,
		speed: 35,
		crew: [2, 7],
		equipment: [
			EQUIPMENT.BALLISTA,
			EQUIPMENT.GROUNDING_STONE,
			EQUIPMENT.SAILS,
		],
		notes: "",
	},
	{
		class: "Fluyt",
		price: 850,
		ac: 15,
		maxhp: 130,
		storage: 17,
		speed: 40,
		crew: [3, 7],
		equipment: [
			EQUIPMENT.CANNON,
			EQUIPMENT.GROUNDING_STONE,
			EQUIPMENT.SAILS,
		],
		notes: "",
	},
	{
		class: "Clipper",
		price: 1000,
		ac: 16,
		maxhp: 120,
		storage: 12,
		speed: 45,
		crew: [4, 9],
		equipment: [
			EQUIPMENT.CANNON,
			EQUIPMENT.GROUNDING_STONE,
			EQUIPMENT.SAILS,
		],
		notes: "",
	},
	{
		class: "Speedboat",
		price: 1100,
		ac: 15,
		maxhp: 90,
		storage: 5,
		speed: 65,
		crew: [1, 4],
		equipment: [
			EQUIPMENT.SAILS,
		],
		notes: "",
	},
	{
		class: "Brigantine",
		price: 1500,
		ac: 16,
		maxhp: 180,
		storage: 14,
		speed: 50,
		crew: [4, 10],
		equipment: [
			EQUIPMENT.MASTERFUL_SAILS,
			EQUIPMENT.CANNON,
			EQUIPMENT.CANNON,
			EQUIPMENT.GROUNDING_STONE,
		],
		notes: "",
	},
	{
		class: "Iron Maiden",
		price: 2000,
		ac: 17,
		maxhp: 500,
		storage: 15,
		speed: 25,
		crew: [4, 10],
		equipment: [
			EQUIPMENT.SAILS,
			EQUIPMENT.CANNON,
			EQUIPMENT.CANNON,
			EQUIPMENT.GROUNDING_STONE,
		],
		notes: "Turns very slowly",
	},
	{
		class: "Heavy Frigate",
		price: 3000,
		ac: 16,
		maxhp: 260,
		storage: 30,
		speed: 55,
		crew: [7, 13],
		equipment: [
			EQUIPMENT.MASTERFUL_SAILS,
			EQUIPMENT.CANNON,
			EQUIPMENT.CANNON,
			EQUIPMENT.GROUNDING_STONE,
			EQUIPMENT.DINGY,
		],
		notes: "",
	},
	{
		class: "Galleon",
		price: 3500,
		ac: 17,
		maxhp: 280,
		storage: 19,
		speed: 60,
		crew: [8, 15],
		equipment: [
			EQUIPMENT.MASTERFUL_SAILS,
			EQUIPMENT.CANNON,
			EQUIPMENT.CANNON,
			EQUIPMENT.CANNON,
			EQUIPMENT.CANNON,
			EQUIPMENT.HARPOON,
			EQUIPMENT.GROUNDING_STONE,
			EQUIPMENT.DINGY,
		],
		notes: "",
	},
	{
		class: "Man'O'War",
		price: 6500,
		ac: 19,
		maxhp: 420,
		storage: 43,
		speed: 70,
		crew: [10, 22],
		equipment: [
			EQUIPMENT.TARGOSIAN_SAILS,
			EQUIPMENT.CANNON,
			EQUIPMENT.CANNON,
			EQUIPMENT.CANNON,
			EQUIPMENT.CANNON,
			EQUIPMENT.CANNON,
			EQUIPMENT.CANNON,
			EQUIPMENT.CANNON,
			EQUIPMENT.CANNON,
			EQUIPMENT.HARPOON,
			EQUIPMENT.HARPOON,
			EQUIPMENT.GROUNDING_STONE,
			EQUIPMENT.DINGY,
		],
		notes: "",
	},
];
// @ts-ignore
ships[null] = {
	class: "Clipper",
	price: 0,
	ac: 0,
	maxhp: 0,
	storage: 0,
	speed: 0,
	crew: [0, 0],
	equipment: [],
};
export const Colors: { [index: string]: string } = {
	teal: "rgba(43, 151, 133, 0.26)",
	yellow: "rgba(187, 184, 33, 0.349)",
	blue: "rgba(33, 112, 187, 0.349)",
	purple: "rgba(101, 48, 187, 0.315)",
	red: "rgba(187, 48, 48, 0.315)",
	green: "rgba(87, 187, 48, 0.26)",
	none: "inherit",
};
export const CommonPlayerNames = [
	"Steve",
	"Salvator",
	"Farly",
	"Stanwick",
	"Laurence",
	"Zackery",
	"Reynaldo",
	"Jaxon",
	"Lampert",
	"Justinus",
	"Dieter",
	"Hanibal",
	"Mandel",
	"Paris",
	"Garin",
	"Shayne",
	"Avery",
	"Cleve",
	"Sewell",
	"Gottlieb",
	"Frantisek",
	"Chapin",
	"Kippy",
	"Westbrook",
	"Justin",
	"Jordon",
	"Tucker",
	"Sadddique",
	"Thaddeus",
	"Delrico",
	"Elric",
	"Norris",
	"Jean-Marie",
	"Alwara",
	"Didina",
	"Kari",
	"Jalyn",
	"Garland",
	"Favor",
	"Korinna",
	"Ashtyn",
	"Gypsy",
	"Shaylee",
	"Cherina",
	"Maren",
	"Appollonia",
	"Evelina",
	"Juleen",
	"Cady",
	"Zyntias",
	"Neneron",
	"Kyrias",
	"Nalas",
	"Emelas",
	"Yfemon",
	"Dantas",
	"Kafykias",
	"Onyzia",
	"Akilis",
	"Aggig",
	"Hagigg",
	"Stuchu",
	"Zeggut",
	"Stugdak",
	"Strangeguts",
	"Mule",
	"Toadbrain",
	"Globflab",
	"Buffoon",
];
export const CommonCargo = [
	"Molasses",
	"Tea",
	"Swords",
	"Bat Guano",
	"Gold",
	"Chocolate",
	"Art",
	"Tacos",
	"Wood",
	"Coconuts",
	"Spiders",
	"Medecine",
	"Water",
	"Grog",
	"Rum",
	"Cannabis",
	"Mangoes",
	"Pineapples",
	"Bananas",
	"Barrels",
	"Cloth",
	"Dyes",
	"Textiles",
	"Tobacco",
	"Cotton",
	"Silver",
	"Firearms",
	"Chickens",
	"Pigs",
	"Alcohol",
	"Precious Gems",
	"Plants",
	"Clothing",
	"Horses",
	"Camels",
	"Kangaroos",
	"Slaves",
	"Pokemon",
	"Cannonballs",
].sort();
export const VeryCommonShipNames = [
	// Hand-Picked Favorites
	"The Swibbly Nippler",
	"The Scourge of the Seas",
	"The Dingy of Despair",
	"The Salty Dog",
	"The Ferry of the Treacherous Channel",
	"The Quintle Slammer",
	"The Barren Buffoon",
	"The Archduke of Ale",
];
export const CommonShipNames = [
	"The Salty Sailor",
	"The Unsinkable",
	"The Broken Boards",
	"The Executioners",
	"The Adventure Coward",
	"The White Pirate",
	"The Evil Ghost",
	"The Death of Wolf",
	"The Seas Sun",
	"The Happy Fortune",
	"The Last Atlantis",
	"The Seas Killer",
	"The Burning Coward",
	"The Privateers Corruption",
	"The Dirty Abandoned",
	"The Poisonous James",
	"The Howling Coward",
	"The Savage Storm",
	"The Hateful Cutlass",
	"The Poisoned Pirate",
	"The Rancid Pirate",
	"The Drunken Pillager",
	"The Fearful Grail of Executioners",
	"The Red Buccaneers",
	"The Bearded Trinity",
	"The Nights Murderer",
	"The Disgrace of the Princess",
	"The Vicious Shark",
	"The Dishonorable Hangman",
	"The Terror",
	"The Pride of the Trinity",
	"The Dirty Caribbean",
	"The Death of Corruption",
	"The Abandoned Barnacle",
	"The Angel of Doom",
	"The Barbaric Serpent",
	"The Black Pearl",
	"The Blood Lightening",
	"The Blood-Thirsty Rover",
	"The Bloody Hangman",
	"The Bone Heart",
	"The Bone Rattler",
	"The Broken Slave",
	"The Broken Soul",
	"The Burning Rose",
	"The Cannon Blocker",
	"The Corrupted Skull",
	"The Crooked Star",
	"The Cursed Hangman",
	"The Cursed Raider",
	"The Cursed Slave",
	"The Dark Howler",
	"The Dark Soul",
	"The Dazzling Pearl",
	"The Dead Bones",
	"The Dead-Man’s Raft",
	"The Death Fire",
	"The Demon Sea-Dog",
	"The Disgraced Anchor",
	"The Dream Chaser",
	"The Drunken James",
	"The Drunken Sailor",
	"The Fearful Diamond",
	"The Fearful Slave",
	"The Ginger Snap",
	"The Golden Cairn",
	"The Golden Eel",
	"The Golden Jewel",
	"The Golden Mermaid",
	"The Golden Rose",
	"The Golden Squid",
	"The Grand Serpent",
	"The Hangman’s Hollow",
	"The Happy Dog",
	"The Happy Sailor",
	"The Hellish Captain",
	"The Hungry Hangman",
	"The Jolly Skull",
	"The Jolly Storm",
	"The Lone Star",
	"The Lost Dreams",
	"The Lost King",
	"The Lost Lagoon",
	"The Lost Soul",
	"The Lost Treasure",
	"The Moon Raider",
	"The Moon Whisperer",
	"The Night Blood",
	"The Night Fighter",
	"The Night of Doom",
	"The Night Soul",
	"The Night Wind",
	"The Ocean Curse",
	"The Old Barnacle",
	"The Old James",
	"The Old Scallywag",
	"The Old Sea Dog",
	"The Old Tide",
	"The Plague Lagoon",
	"The Plague Storm",
	"The Poisoned Arrow",
	"The Poisonous Maid",
	"The Red Hurricane",
	"The Red Pirate",
	"The Red Wave",
	"The Revenge Queen",
	"The Revenge Tide",
	"The Rising Ghost",
	"The Ruthless Raider",
	"The Scream Fire",
	"The Sea Ghost",
	"The Sea of Terror",
	"The Secret Dagger",
	"The Serpent’s Cry",
	"The Seven Seas of WIlliams",
	"The Shadow Storm",
	"The Shark Rider",
	"The Sick Walrus",
	"The Silent Raider",
	"The Soggy Seaweed",
	"The Soul Cairn",
	"The Speedy Sun",
	"The Stinkin Plank",
	"The Stinkin Skull",
	"The Sun Howler",
	"The Tainted Heart",
	"The Tainted Rose",
	"The Thunder Tide",
	"The Thunder Waves",
	"The Vanilla Skyline",
	"The White Night",
	"The White Wave",
	"The Wild Storm",
	"The Wind Raider",
	"The Drunken Squid",
	"The Shallow Mermaid",
	"The Mystic Sea",
	"The Pirate’s Secret",
	"The Dream Stealer",
	"The Shiverin’ Dragon",
	"The Fallen Fish",
	"The Fallen Hook",
	"The New Pearl",
	"The Serpent’s Revenge",
	"The Silent Killer",
	"The Dirty Dragon",
	"The HellFish",
	"The Burning Dragon",
	"The Poseidon’s Revenge",
	"The Curse of Poseidon",
	"The Neptune’s Wave",
	"The Red Tsunami",
	"The Fallen Captain",
	"The Damp Queen",
	"The Fish Fryer",
	"The Dark Shark",
	"The Clumsy Sailor",
	"The Jewel of Atlantis",
	"The Jewel Theif",
	"The Dusty Anchor",
	"The Rusty Bell",
	"The Pretty Coral",
	"The Dreaming Wave",
	"The Tainted Dragon",
	"The Scurvy Wave",
	"The Damned Night",
	"The Squid Blaster",
	"The Rusty Cannon",
	"The Brave Titan",
	"The Stone Shark",
	"The Ghostly Death",
	"The Mystic Sirens",
	"The Pure Sirens",
	"The Devil’s Heart",
	"The Stone Angel",
	"The Fallen Titan",
	"The Wicked Folly",
	"The Deadly Destiny",
	"The Ulgy Kraken",
	"The Soulless Dragon",
	"The Royal Pearl",
	"The Deadly Squid",
	"The Neptune’s Teeth",
	"The Hellish Shark",
	"The Barbaric Ghost",
	"The Lost Mayflower",
	"The Lost Screams of Peter",
	"The Jewel Serpent",
	"The Speedy Slug",
	"The Sunken Seaweed",
	"The Sunken Whale",
	"The Lust Of The Hades",
	"The Mad Sea Rovers",
	"The Hades James",
	"The Mad Trinity",
	"The Mangy Howl",
	"The Cry Of The Murderer",
	"The Horrid Scream",
	"The Gold Return",
	"The Greed Of The Seven Seas",
	"The Night",
	"The Corrupted Abandoned",
	"The Hellish Deceit",
	"The Sea Manta",
	"The Disgraceful Wolf",
	"The Murderers Sea",
	"The Scream",
	"The Drunken Tortuga",
	"The Fall Of Death",
	"The Blind Gold",
	"The Vicious Killer",
	"The Seas Damnation",
	"The Homicidal Ghost",
	"The Captain",
	"The Fortune Grail",
	"The Pillaging Scorn",
	"The Vile Atlantis",
	"The Greed Of The Sun",
	"The Dragons Killer",
	"The Bloodthirsty Damned",
	"The Hellish Slave",
];
